project_id = "httlmwzinkqelzkjjaqf"

[functions.cartoncloud-proxy]
verify_jwt = false

[functions.cartoncloud-soh]
verify_jwt = false

[functions.cartoncloud-webhook]
verify_jwt = false

[functions.google-places-search]
verify_jwt = false

[functions.cartoncloud-create-order]
verify_jwt = false

[functions.cartoncloud-resubmit-order]
verify_jwt = false

[functions.cartoncloud-ai-chat]
verify_jwt = false